export const DEMO_EDITS = [
  {
    id: 'demo_001',
    title: 'Slime Chronicles — Awakening Arc',
    category: 'AMV',
    tags: ['rimuru', 'amv', 'epic'],
    description: 'A dynamic AMV tracing Rimuru\'s rise from human to Demon Lord, cut to orchestral beats.',
    thumbnail: 'https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=640&h=360&fit=crop&q=80',
    videoUrl: '',
    views: 14820,
    featured: true,
    uploadedAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    uploader: 'Crxsyruu',
  },
  {
    id: 'demo_002',
    title: 'Tempest Capital — Timelapse Edit',
    category: 'Cinematic',
    tags: ['cinematic', 'timelapse', 'fantasy'],
    description: 'Cinematic worldbuilding edit showcasing the Great Forest of Jura transformation.',
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=640&h=360&fit=crop&q=80',
    videoUrl: '',
    views: 9340,
    featured: false,
    uploadedAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
    uploader: 'Crxsyruu',
  },
  {
    id: 'demo_003',
    title: 'Milim vs Rimuru — Frame Perfect Cut',
    category: 'Action',
    tags: ['action', 'fight', 'milim'],
    description: 'Frame-perfect action sequence cut with bone-rattling audio design and motion blur.',
    thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=640&h=360&fit=crop&q=80',
    videoUrl: '',
    views: 21750,
    featured: true,
    uploadedAt: Date.now() - 1000 * 60 * 60 * 24 * 8,
    uploader: 'Crxsyruu',
  },
  {
    id: 'demo_004',
    title: 'Slime King — Lofi Chill Mix',
    category: 'Lofi',
    tags: ['lofi', 'chill', 'aesthetic'],
    description: 'Soft lofi aesthetic edit, perfect for those late-night rewatch sessions.',
    thumbnail: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=640&h=360&fit=crop&q=80',
    videoUrl: '',
    views: 7210,
    featured: false,
    uploadedAt: Date.now() - 1000 * 60 * 60 * 24 * 12,
    uploader: 'Crxsyruu',
  },
  {
    id: 'demo_005',
    title: 'Great Sage Whispers — ASMR Edit',
    category: 'ASMR',
    tags: ['asmr', 'ambient', 'calm'],
    description: 'Ambient ASMR edit with soft soundscapes, designed to activate the Great Sage within.',
    thumbnail: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=640&h=360&fit=crop&q=80',
    videoUrl: '',
    views: 5890,
    featured: false,
    uploadedAt: Date.now() - 1000 * 60 * 60 * 24 * 18,
    uploader: 'Crxsyruu',
  },
  {
    id: 'demo_006',
    title: 'Raphael Override — Glitch Art',
    category: 'Glitch',
    tags: ['glitch', 'cyberpunk', 'experimental'],
    description: 'Experimental glitch-art edit inspired by Raphael\'s digital consciousness sequences.',
    thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=640&h=360&fit=crop&q=80',
    videoUrl: '',
    views: 12490,
    featured: true,
    uploadedAt: Date.now() - 1000 * 60 * 60 * 24 * 22,
    uploader: 'Crxsyruu',
  },
]

export const DEMO_STATS = {
  totalViews: 71500,
  totalEdits: 6,
  totalUploads: 6,
  recentActivity: [
    { action: 'New view on', target: 'Milim vs Rimuru', time: '2 min ago' },
    { action: 'New view on', target: 'Slime Chronicles', time: '8 min ago' },
    { action: 'Upload complete', target: 'Raphael Override', time: '22 days ago' },
    { action: 'Featured', target: 'Slime Chronicles', time: '2 days ago' },
    { action: 'New view on', target: 'Great Sage Whispers', time: '1 hour ago' },
  ],
}

export const CATEGORIES = ['All', 'AMV', 'Cinematic', 'Action', 'Lofi', 'ASMR', 'Glitch']
